using System.Collections.Generic;
using System.ComponentModel;

namespace SKF.Standard.Points.Entity
{
    public static class MachineShaft
    {
        public static List<ComboBoxItem> Codes = new List<ComboBoxItem>()
        {
            new ComboBoxItem(){Id = 0, Text = "--SELECT--"},
            new ComboBoxItem(){Id = 1, Text = "IP"},
            new ComboBoxItem(){Id = 2, Text = "IP1"},
            new ComboBoxItem(){Id = 3, Text = "IP2"},
            new ComboBoxItem(){Id = 4, Text = "IP3"},
            new ComboBoxItem(){Id = 5, Text = "IP4"},
            new ComboBoxItem(){Id = 6, Text = "IP5"},
            new ComboBoxItem(){Id = 7, Text = "IP6"},
            new ComboBoxItem(){Id = 8, Text = "IP7"},
            new ComboBoxItem(){Id = 9, Text = "IP8"},
            new ComboBoxItem(){Id = 10, Text = "IP9"},
            new ComboBoxItem(){Id = 11, Text = "IP10"},

            new ComboBoxItem(){Id = 12, Text = "IM"},
            new ComboBoxItem(){Id = 13, Text = "IM1"},
            new ComboBoxItem(){Id = 14, Text = "IM2"},
            new ComboBoxItem(){Id = 15, Text = "IM3"},
            new ComboBoxItem(){Id = 16, Text = "IM4"},
            new ComboBoxItem(){Id = 17, Text = "IM5"},
            new ComboBoxItem(){Id = 18, Text = "IM6"},
            new ComboBoxItem(){Id = 19, Text = "IM7"},
            new ComboBoxItem(){Id = 20, Text = "IM8"},
            new ComboBoxItem(){Id = 21, Text = "IM9"},
            new ComboBoxItem(){Id = 22, Text = "IM10"},
            new ComboBoxItem(){Id = 23, Text = "IM11"},
            new ComboBoxItem(){Id = 24, Text = "IM12"},
            new ComboBoxItem(){Id = 25, Text = "IM13"},
            new ComboBoxItem(){Id = 26, Text = "IM14"},
            new ComboBoxItem(){Id = 27, Text = "IM15"},
            new ComboBoxItem(){Id = 28, Text = "IM16"},
            new ComboBoxItem(){Id = 29, Text = "IM17"},
            new ComboBoxItem(){Id = 30, Text = "IM18"},
            new ComboBoxItem(){Id = 31, Text = "IM19"},
            new ComboBoxItem(){Id = 32, Text = "IM20"},

            new ComboBoxItem(){Id = 32, Text = "OP"},
            new ComboBoxItem(){Id = 33, Text = "OP1"},
            new ComboBoxItem(){Id = 34, Text = "OP2"},
            new ComboBoxItem(){Id = 35, Text = "OP3"},
            new ComboBoxItem(){Id = 36, Text = "OP4"},
            new ComboBoxItem(){Id = 37, Text = "OP5"},
            new ComboBoxItem(){Id = 38, Text = "OP6"},
            new ComboBoxItem(){Id = 39, Text = "OP7"},
            new ComboBoxItem(){Id = 40, Text = "OP8"},
            new ComboBoxItem(){Id = 41, Text = "OP9"},
            new ComboBoxItem(){Id = 42, Text = "OP10"},
            
            new ComboBoxItem(){Id = 43, Text = "PS"},
            new ComboBoxItem(){Id = 44, Text = "PS1"},
            new ComboBoxItem(){Id = 45, Text = "PS2"},
            new ComboBoxItem(){Id = 46, Text = "PS3"},
            new ComboBoxItem(){Id = 47, Text = "PS4"},
            new ComboBoxItem(){Id = 48, Text = "PS5"},
            new ComboBoxItem(){Id = 49, Text = "PS6"},
            new ComboBoxItem(){Id = 50, Text = "PS7"},
            new ComboBoxItem(){Id = 51, Text = "PS8"},
            new ComboBoxItem(){Id = 52, Text = "PS9"},
            new ComboBoxItem(){Id = 53, Text = "PS10"},

            new ComboBoxItem(){Id = 54, Text = "HS"},
            new ComboBoxItem(){Id = 55, Text = "HS1"},
            new ComboBoxItem(){Id = 56, Text = "HS2"},
            new ComboBoxItem(){Id = 57, Text = "HS3"},
            new ComboBoxItem(){Id = 58, Text = "HS4"},
            new ComboBoxItem(){Id = 59, Text = "HS5"},
            new ComboBoxItem(){Id = 60, Text = "HS6"},
            new ComboBoxItem(){Id = 61, Text = "HS7"},
            new ComboBoxItem(){Id = 62, Text = "HS8"},
            new ComboBoxItem(){Id = 63, Text = "HS9"},
            new ComboBoxItem(){Id = 64, Text = "HS10"},

            new ComboBoxItem(){Id = 65, Text = "LS"},
            new ComboBoxItem(){Id = 66, Text = "LS1"},
            new ComboBoxItem(){Id = 67, Text = "LS2"},
            new ComboBoxItem(){Id = 68, Text = "LS3"},
            new ComboBoxItem(){Id = 69, Text = "LS4"},
            new ComboBoxItem(){Id = 70, Text = "LS5"},
            new ComboBoxItem(){Id = 71, Text = "LS6"},
            new ComboBoxItem(){Id = 72, Text = "LS7"},
            new ComboBoxItem(){Id = 73, Text = "LS8"},
            new ComboBoxItem(){Id = 74, Text = "LS9"},
            new ComboBoxItem(){Id = 75, Text = "LS10"},
        };

    }
}
